### ISSUE TITLE
Suggestion: add overload for CombineStatuses that return IStatusGeneric<T>

### ISSUE THREAD

**Issue by cesarsouza** [JonPSmith/GenericServices.StatusGeneric#3]
Hi,

Currently, if someone would like to cut processing short and exit from a method if an operation errors out while still carrying information about the errors in the operation, it would be necessary to write code like this:

```
var status = new StatusGenericHandler<SomeEntity>();

// ... some processing

IStatusGeneric<AnotherEntity> anotherStatus = await myService.SomeOperationThatReturnsAnotherEntity();
if (anotherStatus.HasErrors)
{
    status.CombineStatuses(anotherStatus);
    return status;
}

// ... more processing

return status;
```

However, if there was an extra CombineStatuses overload that would match ``IStatusGeneric<T>`` instead of ``IStatusGeneric``, one would be able to simplify it a little bit to something like this:

```
var status = new StatusGenericHandler<SomeEntity>();

// ... some processing

IStatusGeneric<AnotherEntity> anotherStatus = await myService.SomeOperationThatReturnsAnotherEntity();
if (anotherStatus.HasErrors)
    return status.CombineStatuses(anotherStatus);

// ... more processing

return status;
```

It looks like a tiny change but sometimes it's cumbersome to keep writing the first version if you have lots of operations to call :-) Do you think this would be a good addition to the library?

**Comment by cesarsouza** [comment]
Hi there,

I just wrote some extension methods to make the job of using this library a little bit easier. Maybe they could be useful to others (and maybe a good addition to the library itself too, if you would feel like).

With them, you can write code like:

```cs
var someStatus = await myService.SomeOperation(user.Person.BirthDate);
if (someStatus.Result == null)
    return status.CombineStatuses(someStatus, () => user.Person.BirthDate);
```
or 
```cs
if (user.Person.BirthDate == null)
    return status.AddError(() => user.Person.BirthDate, "Birth date is required");
```

I am also including another version of the ```CopyErrorsToModelState``` method from the EfCore.GenericServices.AspNetCore library (because the original apparently could not handle multi-level property access when the view model was specified explicitly, and when there was no view model it would not include the property names as keys).

The methods are below:

```cs
public static void CopyErrorsToModelState(this IStatusGeneric status, ModelStateDictionary modelState)
{
    if (status.IsValid)
        return;

    foreach (var e in status.Errors)
        foreach (var m in e.ErrorResult.MemberNames)
            modelState.AddModelError(m, e.ErrorResult.ErrorMessage);
}

public static StatusGenericHandler<T> CombineStatuses<T, V, U>(this StatusGenericHandler<T> status, IStatusGeneric<V> other, Expression<Func<U>> expression)
{
    string propertyName = expression.GetMemberPath();

    if (!other.IsValid)
    {
        foreach (var e in other.Errors)
        {
            if (e.ErrorResult.MemberNames.Any())
            {
                foreach (var m in e.ErrorResult.MemberNames)
                    status.AddError(e.ErrorResult.ErrorMessage, propertyName + "." + m);
            }
            else
            {
                status.AddError(e.ErrorResult.ErrorMessage, propertyName);
            }
        }
    }

    return status;
}

public static StatusGenericHandler<T> AddError<T, U>(this StatusGenericHandler<T> status, Expression<Func<U>> expression, string errorMessage)
{
    string propertyName = expression.GetMemberPath();
    status.AddError(errorMessage, propertyName);
    return status;
}

public static string GetMemberPath<T, V>(this Expression<Func<T, V>> expression)
{
    return GetMemberPath((MemberExpression)expression.Body);
}

public static string GetMemberPath<T>(this Expression<Func<T>> expression)
{
    return GetMemberPath((MemberExpression)expression.Body);
}

public static string GetMemberPath(this MemberExpression expression)
{
    var members = new List<string>();
    MemberExpression? m = expression;
    while (m != null)
    {
        members.Add(m.Member.Name);
        m = m.Expression as MemberExpression;
    }
    members.Reverse();
    return String.Join('.', members);
}
```

**Comment by JonPSmith** [comment]
Hi @cesarsouza,

Sorry for the delay in getting back to you but I am very busy so I only look at library issues at the weekend.

I have to say sorry that the documentation for this library was woefully inadequate. I was updating a whole set of libraries and I just needed this out. I have now added a much longer README file with examples of the styles I use.
 
You have some very good ideas, but some are covered by the "Typical patterns" in the updated README file. Also, my [EfCore.GenericServices.AspNetCore](https://github.com/JonPSmith/EfCore.GenericServices.AspNetCore) covers some of the things you need for ASP.NET COre. Obviously using your own Model copy is cleaner, but do have look at my [ValidationHelper](https://github.com/JonPSmith/EfCore.GenericServices.AspNetCore/blob/master/GenericServices.AspNetCore/ValidationHelper.cs) because there are a few extra parts you need for Razor Pages.

Thank you for bringing these issues to me.
