### ISSUE TITLE
Header in StatusGenericHandler.Generic

### ISSUE THREAD

**Issue by Lorenz5600** [JonPSmith/GenericServices.StatusGeneric#5]
Hi Jon,

I'd like to suggest making the generic constructor behave like the regular one:

```
public class StatusGenericHandler<T> : StatusGenericHandler, IStatusGeneric<T>
{
    /// <summary>
    /// This creates a StatusGenericHandler, with optional header (see Header property, and CombineStatuses)
    /// </summary> 
    /// <param name="header"></param>
   public StatusGenericHandler(string header = "") : base(header) {}
}
```

If you like I can create a PR.

Cheers,
Jake

**Comment by JonPSmith** [comment]
Hi @Lorenz5600,

I really don't think it's worth adding this change. It doesn't fix a bug or add a (useful) new feature. So don't bother to create a PR.
